### ISSUE TITLE
receiving ImageData object on then(function(result){})

### ISSUE THREAD

**Issue by jywarren** [canastro/image-filter-threshold#2]
I'm using this with the following code:

```js
  function draw(image, onComplete, options) {

    options = options || {};
    options.threshold = options.threshold || 30;

    var canvas = document.createElement('canvas');
    var context = canvas.getContext('2d');
    context.drawImage(image, 0, 0 );
    var imageData = context.getImageData(0, 0, image.width, image.height);

    var imageThreshold = require('image-filter-threshold');

    var result = imageThreshold({
      data: imageData,
      threshold: options.threshold
    }).then(function (result) {
      image = new Image();
      image.onload = function onLoad() {
        onComplete(image);
      }
     console.log(result)
     image.src = result;
    });

  }
```

But the result as logged out is an `ImageData` object, not something we can assign to `src`. Do we need to encode it as a DataURI? There are a few modules available for that.

**Comment by canastro** [comment]
This modules are returning ImageData so we can chain calls to different modules in the `image-filters` module.

So I just added a helper function called `convertImageDataToCanvasURL` to the image-filter-core, that you can use it like this:

```
var imageFilterCore = require('image-filter-core');

var image = document.createElement('img');
image.setAttribute('src', imageFilterCore.convertImageDataToCanvasURL(imageData));
target.appendChild(image);
```

At the moment this is still at the same branch I added the changes in the last issue, if this is working for you I'll publish all these changes.

**Comment by canastro** [comment]
I'm also updating the README.md file, to reflect this things.

**Comment by canastro** [comment]
I just published version 1.0.0 and deleted the branch I was working on, so make sure to change your package.json to `"image-filter-threshold": "^1.0.0"`.

**Comment by jywarren** [comment]
Thank you very much!!!

**Comment by canastro** [comment]
I'll slowly start adding this changes to the other modules 😄
